apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-labs
  labels:
    app: devopslabs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopslabs
  template:
    metadata:
      labels:
        app: devopslabs
    spec:
      containers:
      - name: devopslabs
        image: tbektleuov/devopslabs:lab7
        ports:
        - containerPort: 8000
