apiVersion: v1
kind: Service
metadata:
  name: exposer
  labels:
    app: devopslabs
spec:
  selector:
    app: devopslabs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer